<?php
/*
Plugin Name: Divine Drip API integration
Description: connect to drip API
Author: Divine Sites
Developer: Eyal Ron
Author URI: https://divinesites.co.il
Text Domain: Divine Sites
version: 1.0
*/

//drip connect variables
// $token = "f33de317ba943021cefc229318aee18e";
$token = esc_attr( get_option('drip_api_token') ); //set your token in plugin setup page

/**
 * just to check if this plugin is up and running
 * @method ddi_check
 * @author Eyal Ron
 * @return boolean        true
 * @date   2018-10-15
 */
function ddi_check(){
  return true;
}

/**
 * update drip subscriber data
 * @method ddi_update_drip_data
 * @param  string              $subscriber subscriber email
 * @param  array               $fields     drip custom fields data
 * @param  array/string        $tags       tags to add to subscriber
 * @return Json                            drip server results
 * @author Eyal Ron
 * @date   2018-10-15
 */
function ddi_update_drip_data($subscriber, $fields, $tags){
  $dataArr = array('subscribers' => [
    [
      'email' => $subscriber,
      'tags' => $tags,
      'custom_fields' => $fields
    ]
  ]);
  $data = json_encode($dataArr);
  // // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
  $ch = curl_init();

  curl_setopt($ch, CURLOPT_URL, "https://api.getdrip.com/v2/9110196/subscribers");
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
  curl_setopt($ch, CURLOPT_POST, 1);
  curl_setopt($ch, CURLOPT_USERPWD, $GLOBALS['token']);

  $headers = array();
  $headers[] = "User-Agent: setDrip";
  $headers[] = 'Content-Type: application/json';
  curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

  $result = curl_exec($ch);
  if (curl_errno($ch)) {
      echo 'Error:' . curl_error($ch);
  }
  curl_close ($ch);

  return $result;
}
//#drip connect

/**
 * add tags to subscriber
 * @method ddi_add_drip_tag
 * @param  string           $subscriber subscriber email
 * @param  array/string     $tag        tags to add to subscriber
 * @author Eyal Ron
 * @date   2018-10-15
 */
function ddi_add_drip_tag($subscriber, $tag){
  error_log("running from ddi plugin");
  $dataArr = array('subscribers' => [
    [
      'email' => $subscriber,
      'tags' => $tag,
      'custom_fields' => $fields
    ]
  ]);
  $data = json_encode($dataArr);
  // // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
  $ch = curl_init();

  curl_setopt($ch, CURLOPT_URL, "https://api.getdrip.com/v2/9110196/subscribers");
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
  curl_setopt($ch, CURLOPT_POST, 1);
  curl_setopt($ch, CURLOPT_USERPWD, $GLOBALS['token']);

  $headers = array();
  $headers[] = "User-Agent: setDrip";
  $headers[] = 'Content-Type: application/json';
  curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

  $result = curl_exec($ch);
  if (curl_errno($ch)) {
      echo 'Error:' . curl_error($ch);
  }
  curl_close ($ch);

  return $result;
}
//#drip connect



/**
 * settings page setup for this plugin
 */
add_action('admin_menu', function() {
    add_options_page( 'divine drip api itegration plugin settings', 'Divine drip api itegration', 'manage_options', 'ddi-plugin', 'ddi_plugin_page' );
});
add_action( 'admin_init', function() {
    register_setting( 'ddi-plugin-settings', 'drip_api_token' );
});
function ddi_plugin_page() {
  ?>
    <div class="wrap">
      <div style="display:flex;align-items:baseline;">
        <h1 style="margin-right:8px;">Divine Drip Integration Settings</h1>
        <span>by <a target="_blank" href="https://divinesites.co.il">Divine Sites</a></span>
      </div>
      <form action="options.php" method="post">
        <?php
          settings_fields( 'ddi-plugin-settings' );
          do_settings_sections( 'ddi-plugin-settings' );
        ?>
        <h3>Drip Settings</h3>
        <table>
            <tr>
              <th>Drip API Token</th>
              <td>
                <input type="text" placeholder="" name="drip_api_token" value="<?php echo esc_attr( get_option('drip_api_token') ); ?>" size="40" />
              </td>
            </tr>
            <tr>
                <td><?php submit_button(); ?></td>
            </tr>
        </table>
      </form>
    </div>
  <?php
}
?>
